### ISSUE TITLE
Java home error message when JAVA_HOME is already set

### ISSUE THREAD

**Issue by Sinapse87** [runningcode/gradle-doctor#144] opened 2021-01-06 23:17 UTC
Hi, I am getting this error message:

9:16 AM	Gradle sync failed: =============================== Gradle Doctor Prescriptions ============================================
				| JAVA_HOME is not set.                                                                                |
				| Please set JAVA_HOME so that switching between Android Studio and the terminal does not trigger a fu |
				| ll rebuild.                                                                                          |
				| To set JAVA_HOME: (using bash)                                                                       |
				| echo "export JAVA_HOME=$(/usr/libexec/java_home)" >> ~/.bash_profile                                 |
				| or `~/.zshrc` if using zsh.                                                                          |
				|  

But my JAVA_HOME is correctly set:

 echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home

It appears the plugin is checking that my JAVA_HOME is exactly /usr/libexec/java_home but this is not what I want it to be.

**Comment by runningcode** [comment] 2021-01-07 09:37
Is Android Studio using your java home to run Gradle as well?

**Comment by Sinapse87** [comment] 2021-01-07 10:02
Yes it is

**Comment by azizbekian** [comment] 2021-01-11 12:41
I also stumble across this issue, but only when trying to push the code within Sourcetree (running on mac).
I have iterm2 as the default terminal. I can verify that JAVA_HOME [is correctly set](https://i.stack.imgur.com/oCDjw.png) in bash_profile and zshrc (pushing code from terminal/iterm2 works as expected).

I wonder if the issue is connected with the Sourcetree or no.

**Comment by runningcode** [comment] 2021-01-11 13:57
Thanks for reporting. Is sourcetree running a Gradle build? Otherwise I don't see how this can be connected.

**Comment by azizbekian** [comment] 2021-01-11 14:00
@runningcode , I have a pre-push hook which runs `./gradlew spotlessCheck`. So, at a point when I try to push to remote the instance of the terminal that sourcetree launches cannot find `JAVA_HOME`, but if I run the same git push from a standalone instance of terminal then the JAVA_HOME gets correctly picked up.

**Comment by runningcode** [comment] 2021-01-11 14:06
The pre-push hook should be run using the same JDK as the rest of your Gradle build. Without this it could be using a different version of JDK which would spawn a new gradle daemon just to run the hook. Please ensure that the hook is run with the same java home and try again.

**Comment by aazizbekyan** [comment] 2021-03-03 12:36
Just to keep further readers updated: the issue is in no means connected with gradle doctor. The issue is within Sourcetree itself which doesn't pick up env variables (see issue [here](https://community.atlassian.com/t5/Bitbucket-questions/SourceTree-Hook-failing-because-paths-don-t-seem-to-be-set/qaq-p/274792)).

**Comment by runningcode** [comment] 2021-03-03 12:46
Thanks for the update! In that case, I'll close this issue.

**Closed by runningcode** 2021-03-03 12:46 UTC
